{% set name = "xcube-resampling" %}
{% set version = "0.1.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xcube-dev/xcube-resampling/archive/v{{ version }}.tar.gz
  sha256: b01361211c1bcb8c586635b9c37972dc3c9c3380aa0ab49af6a753eef9c234d2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - affine >=2.2
    - dask >=2021.6
    - dask-image >=0.6
    - numba >=0.52
    - numpy >=1.16
    - pyproj >=3.0
    - xarray >=2024.7
    - zarr >=2.11,<3
test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - xcube_resampling

about:
  summary: A xcube package providing low-level, dask-aware spatial resampling algorithms.
  home: https://github.com/xcube-dev/xcube-resampling
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: xcube-resampling is an xcube extension that provides spatial resampling algorithms for Earth Observation (EO) raster datasets.
  doc_url: https://xcube-dev.github.io/xcube-resampling/
  dev_url: https://github.com/xcube-dev/xcube-resampling

extra:
  recipe-maintainers:
    - clarasb
    - b-yogesh
    - konstntokas
    - pont-us
    - TejasMorbagal
    - thomasstorm
    - TonioF
